### ISSUE TITLE
Column active_time missing in postgres < 14

### ISSUE THREAD

**Issue by MarcWort** [prometheus-community/postgres_exporter#1044]
As @dbakit already said in https://github.com/prometheus-community/postgres_exporter/pull/961#issuecomment-1855052713 `active_time` is only available on postgres >=14. 

Maybe there is a need for versioning pg versions in the collector package?

**Comment by sysadmind** [comment]
There is support for versions in the collector package. The instance struct has the postgres version for comparison. 

https://github.com/prometheus-community/postgres_exporter/blob/master/collector/instance.go
