### ISSUE TITLE
`pg_stat_statements` doesn't return query text

### ISSUE THREAD

**Issue by Kaslie** [prometheus-community/postgres_exporter#1054]
I've checked to the code [pg_stat_statements](https://github.com/prometheus-community/postgres_exporter/blob/master/collector/pg_stat_statements.go#L95) found out it doesn't return the `query text`.
Are there any reason that the `pg_stat_statements` collector doesn't return query text ?

it's only return queryid, are there any way to show the query text using `queryid` ? Show to me if there are any.

I know that I can use custom queries, but it is deprecated, So I just want to use the collector if possible.

**Proposal**
add 1 more column to the query like:
```
SELECT
		pg_get_userbyid(userid) as user,
		pg_database.datname,
		pg_stat_statements.query, -- added here
		pg_stat_statements.queryid,
		pg_stat_statements.calls as calls_total,
		pg_stat_statements.total_exec_time / 1000.0 as seconds_total,
		pg_stat_statements.rows as rows_total,
		pg_stat_statements.blk_read_time / 1000.0 as block_read_seconds_total,
		pg_stat_statements.blk_write_time / 1000.0 as block_write_seconds_total
		FROM pg_stat_statements
	JOIN pg_database
		ON pg_database.oid = pg_stat_statements.dbid
	WHERE
		total_exec_time > (
		SELECT percentile_cont(0.1)
			WITHIN GROUP (ORDER BY total_exec_time)
			FROM pg_stat_statements
		)
	ORDER BY seconds_total DESC
	LIMIT 100;
```

Thank you

**Comment by isaiasanchez** [comment]
The query text could be extremely huge to be displayed by the collector, you can use the queryid and go back to the database and get the query text if needed.

**Comment by Kaslie** [comment]
Got it. Thank you @isaiasanchez
