### ISSUE TITLE
[Question]  posgres_export in RDS

### ISSUE THREAD

**Issue by andel7** [prometheus-community/postgres_exporter#184]
I know it's more postgres admin question but can you clarify this part in documentation:
-- If deploying as non-superuser (for example in AWS RDS)
-- GRANT postgres_exporter TO :MASTER_USER;

First what that does? - If I understand correctly it adds membership of  :MASTER_USER to postgres_exporter which is User or Schema?!

Second - :MASTER_USER is a placeholder or actuall user/role in AWS RDS ?

Thanks for your help in advance!

**Comment by wrouesnel** [comment]
I don't use RDS so the documentation here is contributed, unfortunately.

**Comment by lathonez** [comment]
Hey,

I came here searching for the same answer.

On RDS, without running this, on the the next command I get:

```
postgres=> CREATE SCHEMA prometheus_exporter AUTHORIZATION prometheus_exporter;
ERROR:  must be member of role "prometheus_exporter"
```

So first I run:

```
GRANT postgres_exporter TO :MASTER_USER;
```

Where `:MASTER_USER;` is my currently running user, withe the `rds_superuser` role (so yeah it's just a placeholder).

I guess this is only required to create the schema and could be dropped after.

The docs could be clearer, for me `:MASTER_USER` is an odd syntax and looks like it could be some kind of postgres reserved variable.

Thanks

**Comment by wrouesnel** [comment]
Good note about the documentation - PRs very welcome if you have a clearer write up, but I'll make a note to improve it.
