### ISSUE TITLE
Suggest using `pg_monitor` role for PostgreSQL >= 10

### ISSUE THREAD

**Issue by ilmari** [prometheus-community/postgres_exporter#258]
As of PostgreSQL 10, there are [built-in roles](https://www.postgresql.org/docs/10/default-roles.html) that give access to extra statistics without needing to be superuser.

The documentation should suggest using creating an unprivileged user and granting the `pg_monitor` role to it.

**Comment by wrouesnel** [comment]
If someone could test what works for this, I'd be happy to update.

**Comment by crimean-celica** [comment]
> If someone could test what works for this, I'd be happy to update.

It works fine with 12.6

**Comment by ilmari** [comment]
Assuming `postgres_exporter` runs as the OS user `prometheus`, either of the following will work.

In shell, as an OS user that has superuser or createrole access (e.g. `postgres` on most OSes):
```sh
createuser --role pg_monitor prometheus
```
or in `psql`, as a a similarly privileged user:
```sql
create user prometheus in role pg_monitor;
```
