### ISSUE TITLE
panic: Unknown unit for runtime variable: "64kB"

### ISSUE THREAD

**Issue by wanghy8166** [prometheus-community/postgres_exporter#372]
in PostgreSQL 12.1
Error log:
panic: Unknown unit for runtime variable: "64kB"

**Comment by zhoulhb** [comment]
I also see this error，my pg version == 10.7 and os is centos 7.6

**Comment by pppoke** [comment]
so am I, someone help??

**Comment by sysadmind** [comment]
Fixed in #740
