### ISSUE TITLE
Unexpected `go_` metrics showing up that cannot be disabled in exporter

### ISSUE THREAD

**Issue by akamensky** [prometheus-community/postgres_exporter#384]
Details:

- Exporter version 0.8.0 (downloaded from published releases)
- Postgres 10.9
- Envrionment Centos 7.5 64-bit

Steps:

1. Make this exporter barely run (see my previous reports)
2. Use queries.yml from this repo and use `--disable-default-metrics --disable-settings-metrics --extend.query-path=queries.yml` arguments when running this agent

Expected outcome:

ONLY metrics defined in queries.yml show up at metrics page

Actual outcome:

GO runtime metrics appearing on the page. I am not planning on monitoring internals of this exporter, I am trying to monitor database, I believe these should be never shown there.

**Comment by ariep** [comment]
Agreed. I wonder if the `--disable-default-metrics` and `--disable-settings-metrics` just don't work, or that they don't cover everything. Either way it's not great if you have only a few queries that you want metrics for, and the exporter adds around 50 metrics of its own.

**Comment by SuperQ** [comment]
This exporter is for monitoring database servers, not databases.

If you want to only monitor business data, use an SQL exporter like https://github.com/free/sql_exporter.

**Comment by ariep** [comment]
Thanks for the reference SuperQ, that's very useful!
