### ISSUE TITLE
Postgresql 12.3 support

### ISSUE THREAD

**Issue by oronKarmona** [prometheus-community/postgres_exporter#460]
Hi there, 
In your documentation you mentioned that the tested versions are 9-11.
Eventhough, it looks like the exporter works well with version 12.3.
Can you mention problems that can occur by using the exporter on this version? (or maybe there are none :)) 
Thanks

**Comment by splokhikh** [comment]
@oronKarmona I have a problems with Postgres 12. In exporter logs I see two errors:
```
Error running query on database "/var/run/postgresql/:5432": pg_rel_storage_stats pq: column tbl.relhasoids does not exist
Error running query on database "/var/run/postgresql/:5432": pg_stat_statements pq: relation "pg_stat_statements" does not exist
```

As a result not all metrics available.
Guys, any plan to add full Postgres 12 support?

**Comment by kadaffy** [comment]
@splokhikh,  I've test it with postgres version 11, 12 and 13 and works really fine:

postgres-exporter version: 0.8
postgres version: 13

```
$ curl http://localhost:9187/metrics | grep pg_static
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 92680    0 92680    0     0  2207k      0 --:--:-- --:--:-- --:--:-- 2207k
# HELP pg_static Version string as reported by postgres
# TYPE pg_static untyped
pg_static{cluster_name="local",server="postgres:5432",short_version="13.0.0",version="PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit"} 1
```
If you use some metrics that use some shared libraries like `pg_stat_statement` you need to make sure you added it to your postgres configuration before start the postgres-exporter service. Otherwise the other metrics will be affected.

**Comment by pomazanbohdan** [comment]
I have log in postgres_exporter
`time="2020-11-17T08:08:26Z" level=debug msg="Querying Postgres Version on \"postgres.pomazan:5432\"" source="postgres_exporter.go:1388",
time="2020-11-17T08:08:26Z" level=debug msg="Querying pg_setting view on \"postgres.pomazan:5432\"" source="pg_setting.go:15",
time="2020-11-17T08:08:26Z" level=debug msg="Querying namespace:  pg_stat_database" source="postgres_exporter.go:1323",
time="2020-11-17T08:08:26Z" level=debug msg="Querying namespace:  pg_stat_database_conflicts" source="postgres_exporter.go:1323",
time="2020-11-17T08:08:26Z" level=debug msg="Querying namespace:  pg_locks" source="postgres_exporter.go:1323",
time="2020-11-17T08:08:26Z" level=debug msg="Querying namespace:  pg_stat_replication" source="postgres_exporter.go:1323",
time="2020-11-17T08:08:26Z" level=debug msg="Querying namespace:  pg_stat_archiver" source="postgres_exporter.go:1323",
time="2020-11-17T08:08:26Z" level=debug msg="Querying namespace:  pg_stat_activity" source="postgres_exporter.go:1323",
time="2020-11-17T08:08:26Z" level=debug msg="Querying namespace:  pg_stat_bgwriter" source="postgres_exporter.go:1323",`

I change in postgresql.conf
`# - Query and Index Statistics Collector -

track_activities = on
track_counts = on
track_io_timing = on
track_functions = all			# none, pl, all
track_activity_query_size = 1024	# (change requires restart)
stats_temp_directory = 'pg_stat_tmp'


# - Monitoring -

log_parser_stats = on
log_planner_stats = on
log_executor_stats = on
log_statement_stats = on`

End postgres_exporter run

**Comment by wrouesnel** [comment]
Unfortunately my time to work on postgres_exporter has been close to 0 for the last year, and the build environment has moved around a lot underneath it since then so keeping CI in a place where proving new versions worked hasn't been the most feasible.

**Comment by juanradiego** [comment]
Postgresql 12 support would be very useful! This is the best exporter for postgresql in Prometheus and this feature for me is a must, I look forward for it.

Thanks to all people involve in this project.

**Comment by SuperQ** [comment]
I'm updating the integration tests for various versions:

https://github.com/prometheus-community/postgres_exporter/pull/486

**Comment by SuperQ** [comment]
v0.9.0 has been released, the integration tests are passing, although maybe not as robust as some of the original tests.
