### ISSUE TITLE
sha256sums.txt files with releases

### ISSUE THREAD

**Issue by jbouter** [prometheus-community/postgres_exporter#470]
Kindly supply `sha256sums.txt` files with the releases, which makes verification of the downloaded archives easier during automated installation.  See [node_exporter](https://github.com/prometheus/node_exporter/releases/tag/v1.0.1) releases as an example.

**Comment by SuperQ** [comment]
Yes, this would be a good idea.

IMO, it might be worth switching to either [promu](https://github.com/prometheus/promu) or [goreleaser](https://goreleaser.com/) to cut new versions.

**Comment by jbouter** [comment]
`goreleaser` looks beautiful. They have some spot-on documentation on [releasing with GitHub Actions](https://goreleaser.com/ci/actions/) as well :-)
