### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by britcey** [prometheus-community/postgres_exporter#471]
Can we have a new release cut?

This is included as part of https://github.com/lest/prometheus-rpm but I'd love a version that has the recent updates included - especially #426

**Comment by bchahn** [comment]
A new release would be helpful for us as well.

**Comment by SuperQ** [comment]
+1. It might also be time to switch to Go modules for dependency management.

**Comment by SuperQ** [comment]
Almost done, just finishing up integration tests and some other cleanup.

**Comment by bchahn** [comment]
Thanks a lot :-)

**Comment by SuperQ** [comment]
v0.9.0 is released.
