### ISSUE TITLE
Typo in the repo's description 

### ISSUE THREAD

**Issue by NikolayS** [prometheus-community/postgres_exporter#472]
"A PostgresSQL metric exporter for Prometheus" -- GitHub repo description has a typo -- it's very visible in Google SERP:

![Screen Shot 2021-01-22 at 15 53 58](https://user-images.githubusercontent.com/1345402/105560910-217e3300-5cca-11eb-80ae-fe8ed8ea71b6.png)

**Comment by SuperQ** [comment]
Fixed
