### ISSUE TITLE
Prometheus Community

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/postgres_exporter#475]
Is there any interest in moving this exporter to https://github.com/prometheus-community?

**Comment by roidelapluie** [comment]
I have business interest in this, I'd like to have this in the prometheus-community so we can use the "common" patterns (promu, go.mod) which would make it easier to me to contribute.

What my customer needs is the TLS/authentication features (based on https://github.com/prometheus/exporter-toolkit), that I am willing to contribute to this exporter.

**Comment by wrouesnel** [comment]
@SuperQ I'd be happy to move this to Prometheus community. Unfortunately my day-to-day use of Postgres somehow has only fallen since I originally wrote it, so it would be good to get more maintainer eyes across it.

**Comment by SuperQ** [comment]
I've created a team and sent an invite.

**Comment by SuperQ** [comment]
Done!
