### ISSUE TITLE
Apply for Linux on Power （linux ppc64le and ppc64) platform support

### ISSUE THREAD

**Issue by DBres4Power** [prometheus-community/postgres_exporter#481]
Now the 'var platforms []Platform' in file magefile.go doesn't include Linux on Power (ppc64le and ppc64) platform, would you please add linux ppc64le and ppc64) platform support like following:

// Supported platforms
var platforms []Platform = []Platform{
        {"linux", "amd64", ""},
        {"linux", "386", ""},
        {"linux", "arm64", ""},
        {"linux", "mips64le", ""},
        **_{"linux", "ppc64", ""},
        {"linux", "ppc64le", ""},_**
        {"darwin", "amd64", ""},
        {"darwin", "386", ""},
        {"windows", "amd64", ".exe"},
        {"windows", "386", ".exe"},
        {"freebsd", "amd64", ""},
}

Thank you!

**Comment by SuperQ** [comment]
We're going to switch from mage to promu.

https://github.com/prometheus-community/postgres_exporter/issues/478
