### ISSUE TITLE
no such host

### ISSUE THREAD

**Issue by AliA74** [prometheus-community/postgres_exporter#482]
Hi

I receive this log using _postgres_exporter_ as explained in docs using docker:
` dial tcp: lookup \"postgres: no such host" source="postgres_exporter.go:1608"`

The host exists and both containers are on the same network. Other containers on the same network are able to reach 'postgres' without problem. I could not verify if I can ping the 'postgres' from inside container because the container lacks ping command and I don't have root privileges to install it.

docker-compose.yml:
`version: '3.7'

services:
  postgres-reporter:
    image: wrouesnel/postgres_exporter
    container_name: "postgres-reporter"
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime
    ports:
    - "9187:9187"
    environment:
      - DATA_SOURCE_URI="postgres/xxx?sslmode=disable"
      - DATA_SOURCE_USER="postgres"
      - DATA_SOURCE_PASS="zzz"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

networks:
  default:
    external:
      name: baghenegar
`

Any idea how to fix this or what is causing this?

**Comment by AliA74** [comment]
I created another Image based on Centos 7, added the binary. It still can't connect to the database.
I can now confirm that the database is reachable from the exporter container using ping command.

**Comment by 0x6a6f** [comment]
Hi, can tou try without the quotes in your *docker-compose.yml* ?
```yaml
environment:
  - DATA_SOURCE_URI=postgres/xxx?sslmode=disable
  - DATA_SOURCE_USER=postgres
  - DATA_SOURCE_PASS=zzz
```

**Comment by AliA74** [comment]
@0x6a6f It got fixed by doing what you said. You saved me.
Thanks.
