### ISSUE TITLE
Add support for multi-target exporter scraping

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/postgres_exporter#487]
We should deprecate supporting multiple targets in the exporter with the [multi-target exporter pattern](https://prometheus.io/docs/guides/multi-target-exporter/).

This follows Prometheus best practices better.

**Comment by tpoindessous** [comment]
Hi !

You can see another example here : https://github.com/oliver006/redis_exporter

thanks !

**Comment by SuperQ** [comment]
@tpoindessous Care to make an implementation? The other PR author seems to have vanished.

**Comment by zerthimon** [comment]
Also interested in this feature. Currently I have to run separate prometheus-postgres-exporter process for every master and replicas.

**Comment by zerthimon** [comment]
While at it ) it would be nice if this could be configured in a prometheus job, to work with discovery, etc. This is implemented in redis-exporter:
  - job_name: redis_exporter
    static_configs:
      - targets:
        - redis://redis1:6379
        - redis://redis2:6379
        - redis://redis-etc:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-redis-exporter:9121

The redis-exporter is then answers on URIs like this `http://prometheus-redis-exporter:9121/scrape?target=redis://redis1:6379`
