### ISSUE TITLE
RDS snapshot metrics

### ISSUE THREAD

**Issue by gmulpuri** [prometheus-community/postgres_exporter#490]
Hello, I am trying to leverage Postgres exporter to get the recent RDS automated snapshot information. If in any case, there was no recent RDS snapshot in 24 hours I want to be notified via Prometheus. I have tried various other metrics and exporters, which did not suffice. Is there any opportunity for you guys to add this feature in the near release items. Thanks.

**Comment by SuperQ** [comment]
This sounds like an AWS-specific question. You'll have to ask Amazon support about metrics for this. Perhaps there are Cloudwatch metrics for this and you can use the [cloudwatch_exporter](https://github.com/prometheus/cloudwatch_exporter).

**Comment by gmulpuri** [comment]
Thank you.
