### ISSUE TITLE
Wrong versioning in new release (0.9)

### ISSUE THREAD

**Issue by csabka** [prometheus-community/postgres_exporter#492]
postgres_exporter-0.9.0.linux-amd64.tar.gz contains
./postgres_exporter  --version
**postgres_exporter 0.0.1-rev (built with go1.15.8)**

**Comment by SuperQ** [comment]
Oops! I guess we're not injecting the build time variable correctly.

**Comment by SuperQ** [comment]
This will get fixed in the next release.
