### ISSUE TITLE
function pg_current_wal_lsn() not exists on 9.5.x

### ISSUE THREAD

**Issue by csabka** [prometheus-community/postgres_exporter#495]
bug in new feature in 0.9.0 
pg_replication_slots pq: function pg_current_wal_lsn() does not exist" source="postgres_exporter.go:1503"

pg_current_wal_lsn() function only exists from 10 version.

There should be a bool to switch of this new feature

**Comment by roidelapluie** [comment]
thanks for your report. we could simply only query it in psql 10+

**Comment by nnz1024** [comment]
Hi @roidelapluie !
Still got this problem. It appears in https://github.com/prometheus-community/postgres_exporter/blob/c51a28f5f086f4f011ad9b4c9dcd4e78d1cb2c12/cmd/postgres_exporter/postgres_exporter.go#L435
This query is marked as `>=9.4.0` and contains `pg_current_wal_lsn()` which introduced only in Postgres 10.

**Comment by nicholasklem** [comment]
Any progress on reviewing this PR? :+1:

**Comment by halvaborsch** [comment]
Think we can make it even better.

**Comment by WalkerWalker** [comment]
this problem still exists in version 0.12.0, postgres 9.6

log from exporter
```
ts=2023-03-27T15:32:00.188Z caller=collector.go:194 level=error msg="collector failed" name=replication_slot duration_seconds=0.011199623 err="pq: function pg_current_wal_lsn() does not exist"
```

log from postgres
```
postgres_1                        | ERROR:  function pg_current_wal_lsn() does not exist at character 25
postgres_1                        | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
postgres_1                        | STATEMENT:  SELECT
postgres_1                        | 				slot_name,
postgres_1                        | 				pg_current_wal_lsn() - '0/0' AS current_wal_lsn,
postgres_1                        | 				coalesce(confirmed_flush_lsn, '0/0') - '0/0',
postgres_1                        | 				active
postgres_1                        | 			FROM
postgres_1                        | 				pg_replication_slots;
```this problem still exists in version 0.12.0, postgres 9.6

log from exporter
```
ts=2023-03-27T15:32:00.188Z caller=collector.go:194 level=error msg="collector failed" name=replication_slot duration_seconds=0.011199623 err="pq: function pg_current_wal_lsn() does not exist"
```

log from postgres
```
postgres_1                        | ERROR:  function pg_current_wal_lsn() does not exist at character 25
postgres_1                        | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
postgres_1                        | STATEMENT:  SELECT
postgres_1                        | 				slot_name,
postgres_1                        | 				pg_current_wal_lsn() - '0/0' AS current_wal_lsn,
postgres_1                        | 				coalesce(confirmed_flush_lsn, '0/0') - '0/0',
postgres_1                        | 				active
postgres_1                        | 			FROM
postgres_1                        | 				pg_replication_slots;
```

**Comment by rEVOLution-BlackMamba** [comment]
> this problem still exists in version 0.12.0, postgres 9.6
> 
> log from exporter
> 
> ```
> ts=2023-03-27T15:32:00.188Z caller=collector.go:194 level=error msg="collector failed" name=replication_slot duration_seconds=0.011199623 err="pq: function pg_current_wal_lsn() does not exist"
> ```
> 
> log from postgres
> 
> ```
> postgres_1                        | ERROR:  function pg_current_wal_lsn() does not exist at character 25
> postgres_1                        | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
> postgres_1                        | STATEMENT:  SELECT
> postgres_1                        | 				slot_name,
> postgres_1                        | 				pg_current_wal_lsn() - '0/0' AS current_wal_lsn,
> postgres_1                        | 				coalesce(confirmed_flush_lsn, '0/0') - '0/0',
> postgres_1                        | 				active
> postgres_1                        | 			FROM
> postgres_1                        | 				pg_replication_slots;
> ```
> 
> in version 0.10.0, the problem does not appear.

Same problem over here. Same version of postgres and postgres-exporter.

**Comment by halvaborsch** [comment]
you're mistaken, this is a new code that appeared in version 0.12.0

**Comment by halvaborsch** [comment]
https://github.com/prometheus-community/postgres_exporter/pull/747/files

version <10 were forgotten... again :(

**Comment by sysadmind** [comment]
It would appear that support for postgres < 10 was missed in that PR. Postgres 9 is not a version that we test against in our CI system. It's end of support so we don't go out of our way to test on it, but we don't intentionally break compatibility when we can avoid it. I think we could add that second query back to support < 10, but it would require some work to architect a maintainable system to handle different queries for different server versions.
