### ISSUE TITLE
Release Docker image with latest release

### ISSUE THREAD

**Issue by mreise** [prometheus-community/postgres_exporter#505]
Hi, thank you for releasing v0.9.0. When I have a look to https://hub.docker.com/r/wrouesnel/postgres_exporter, I don't see any images with tag version v0.9.0. Do you have released a new image version, too?

**Comment by SuperQ** [comment]
Docker images have moved to [`prometheuscommunity/postgres-exporter`](https://hub.docker.com/r/prometheuscommunity/postgres-exporter/tags).
