### ISSUE TITLE
--auto-discover-databases is broken and unsafe when used with UNIX domain sockets or non-superuser setups

### ISSUE THREAD

**Issue by andrejpodzimek** [prometheus-community/postgres_exporter#513]
I was curious about what `--auto-discover-databases` does. It sounded reasonable based on the documentation and I thought I **should** have it set (either to make the exporter work at all or to get the most of it, in some sense). *(Do I need it?)*

I’m using UNIX domain sockets and a non-superuser setup, as already described in #512 (`postgresql:///?dbname=postgres&user=postgres_exporter&password=CENSORED&host=/run/postgresql/&port=5432`).

There were two bad surprises:

0. **Enabling the flag exposed my `postgres_exporter` user’s password in plain text in the logs.**
    * The password is normally obscured when the “non-keyword” format of the PostgreSQL URI is used.
    * Password hiding does **not** happen with the “keyword” format shown above.
0. `prometheus_postgres_exporter` attempted to connect to each database it found, which (of course) kept failing, because:
    * It failed to honor the rest of the database URI and attempted to use TCP instead of UNIX domain sockets (which failed `pg_hba.conf` checks).
    * It expected that it should be allowed to connect to all the databases. (Why? Is that necessary?) This is also disallowed in `pg_hba.conf` (because it’s not quite obvious why it should be allowed).

The following log snipeet shows the issues. “`THIS_WAS_LOGGED_IN_PLAIN_TEXT`” shows where the password was and “`SOME_DATABASE_NAME_N`” are placeholders for some of the databases that `--auto-discover-databases` found and tried to connect to (using TCP instead of UNIX domain sockets and trying the same user credentials as for the `postgres` database).

```
time="2021-04-03T04:03:03+02:00" level=info msg="Starting Server: [::1]:9187" source="postgres_exporter.go:1850"
time="2021-04-03T04:03:05+02:00" level=info msg="Established new database connection to \"/run/postgresql/:5432\"." source="postgres_exporter.go:983"
time="2021-04-03T04:03:05+02:00" level=info msg="Established new database connection to \"SOME_DATABASE_NAME_1:5432\"." source="postgres_exporter.go:983"
time="2021-04-03T04:03:06+02:00" level=error msg="Error opening connection to database (postgresql://SOME_DATABASE_NAME_1?dbname=postgres&user=postgres_exporter&password=THIS_WAS_LOGGED_IN_PLAIN_TEXT&host=/run/postgresql/&port=5432): pq: pg_hba.conf rejects connection for host \"::1\", user \"postgres_exporter\", database \"postgres\", SSL on" source="postgres_exporter.go:1621"
time="2021-04-03T04:03:06+02:00" level=info msg="Established new database connection to \"SOME_DATABASE_NAME_2:5432\"." source="postgres_exporter.go:983"
time="2021-04-03T04:03:07+02:00" level=error msg="Error opening connection to database (postgresql://SOME_DATABASE_NAME_2?dbname=postgres&user=postgres_exporter&password=THIS_WAS_LOGGED_IN_PLAIN_TEXT&host=/run/postgresql/&port=5432): pq: pg_hba.conf rejects connection for host \"::1\", user \"postgres_exporter\", database \"postgres\", SSL on" source="postgres_exporter.go:1621"
time="2021-04-03T04:03:07+02:00" level=info msg="Established new database connection to \"SOME_DATABASE_NAME_3:5432\"." source="postgres_exporter.go:983"
time="2021-04-03T04:03:08+02:00" level=error msg="Error opening connection to database (postgresql://SOME_DATABASE_NAME_3?dbname=postgres&user=postgres_exporter&password=THIS_WAS_LOGGED_IN_PLAIN_TEXT&host=/run/postgresql/&port=5432): pq: pg_hba.conf rejects connection for host \"::1\", user \"postgres_exporter\", database \"postgres\", SSL on" source="postgres_exporter.go:1621"
time="2021-04-03T04:03:08+02:00" level=info msg="Semantic Version Changed on \"/run/postgresql/:5432\": 0.0.0 -> 13.2.0" source="postgres_exporter.go:1552"
```

**Comment by ticpu** [comment]
I had the same use-case of monitoring multiple databases and clusters using Unix socket. So, just in case it is useful for anyone,  I made a simple Python daemon that spawns one instance of the exporter per PostgreSQL cluster and exposes the data on a single endpoint. https://github.com/ticpu/tools/tree/master/multi-postgres-exporter

dpkg-buildpackage that and it should install and work instantly when the service is enabled.

**Comment by sysadmind** [comment]
We have worked on refactoring how that data is stored internally. I believe the v0.12.0 release should resolve the password being logged in plain text.
