### ISSUE TITLE
Unable to connect to Azure PG Flexible

### ISSUE THREAD

**Issue by luannnh** [prometheus-community/postgres_exporter#517]
Hi,
I'm playing around with _postgres-exporter_ (0.9.0) and _Azure PG Flexible_ (v12).  My simple lab has 1 virtual machine and 1 Azure PG Flex server, they are on the same private network. 
Here's my test:
```
export DATA_SOURCE_NAME="postgresql://test:test@test00.postgres.database.azure.com:5432/postgres?sslmode=disable"  
./postgres_exporter --log.level="debug"
```
Here's log 
```
INFO[0678] Established new database connection to "test00.postgres.database.azure.com:5432".  source="postgres_exporter.go:983"
ERRO[0679] Error opening connection to database (postgresql://test:PASSWORD_REMOVED@test00.postgres.database.azure.com:5432/postgres?sslmode=disable): pq: no pg_hba.conf entry for host "xxx.xxx.xxxx.xxx", user "test", database "postgres", SSL off  source="postgres_exporter.go:1621"
```
There is no problem with the database connection when using _psql_ or _psycopg2_. I think it might be a bug of _postgres-exporter_. 

Thanks.

**Comment by mbanck** [comment]
Are you sure Azure Flexible server allows non-SSL connections? Did you recheck your psql connection is identical? The error message you got implies you're trying to connect in a way that is not allowed by the server configuration

**Comment by luannnh** [comment]
@mbanck thanks. The issue is fixed now. Solution = removing "sslmode=disable"
