### ISSUE TITLE
v0.10.0?

### ISSUE THREAD

**Issue by jameslorda** [prometheus-community/postgres_exporter#527]
Could we get a new release for this project please?

**Comment by martbhell** [comment]
If you do, would be nice to keep the same convention as last time: 
 - tag: v0.9.0
 - filename containing 0.9.0 without the v

**Comment by ceamoroz** [comment]
Please release a new version including https support added in commit https://github.com/prometheus-community/postgres_exporter/commit/be790e12ff072637f7d5ad0cff35dc55aea2b8ff.

**Comment by sarthak40** [comment]
\cc @SuperQ

**Comment by mbanck** [comment]
@SuperQ  There's been a release (0.10.0) since, so this should be closed.
