### ISSUE TITLE
Add ability to use encrypted password

### ISSUE THREAD

**Issue by leonsery** [prometheus-community/postgres_exporter#536]
## Proposal
**Need to be able to encrypt password passed to exporter. Our customers don't like that PG password is passed to exporter in plain text via command line of env variable.**

**Comment by roidelapluie** [comment]
Thank you, even if encrypted, the exporter would need to un-encrypt it. Therefore it would be security  by obscurity.

I suggest you to use TLS certificates or use a securely protected file to store the password (DATA_SOURCE_PASS_FILE env variable).
