### ISSUE TITLE
Error "WAL control functions cannot be executed during recovery" for pg_replication_slots

### ISSUE THREAD

**Issue by dan-aksenov** [prometheus-community/postgres_exporter#547]
**What did you do?**
Simply running exporter `0.0.1-rev (built with go1.15.8)`

**What did you expect to see?**
I expect no errors

**What did you see instead? Under which circumstances?**
```
ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
STATEMENT:
                                SELECT slot_name, database, active, pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)
                                FROM pg_replication_slots

```

**Environment**

* System information:

	insert output of `uname -srm` here
`Linux 5.4.0-66-generic x86_64`

* postgres_exporter version:

	insert output of `postgres_exporter --version` here
`postgres_exporter 0.0.1-rev (built with go1.15.8)`

* postgres_exporter flags:

```
/opt/postgres_exporter/postgres_exporter --web.listen-address=:9187 --log.level=warn --extend.query-path=/opt/postgres_exporter/queries.yaml
```

* PostgresSQL version:

	insert PostgreSQL version here
11.8

* Logs:
```
insert logs relevant to the issue here
```

While looking here
https://github.com/prometheus-community/postgres_exporter/blob/134e90888526d95c8159018c4dcb38fe526f87b7/cmd/postgres_exporter/postgres_exporter.go#L431-L443
I see no pg_is_in_recovery check

**Comment by michael-todorovic** [comment]
Hello,
We identified the issue at my company with standby clusters and we're currently working on a fix ;) I was forking the repo to send the PR today or tomorrow

**Comment by maudrid** [comment]
Thanks, this fixed my issue also.

**Comment by mhbahmani** [comment]
Hi,

This issue is open since 2021! I was wondering when it gets fixed.
I encountered this issue on postgresql 14.

Thanks.
