### ISSUE TITLE
pg_replication_is_replica missing

### ISSUE THREAD

**Issue by david-peters-aitch2o** [prometheus-community/postgres_exporter#563]
**What did you do?**
installed 0.10.0 on a cluster of 3 nodes

**What did you expect to see?**
I expect pg_replication_is_replica to show if the node it's running on is a replica

**What did you see instead? Under which circumstances?**
no metric available

**Environment**

* System information:

`Linux 4.18.0-305.7.1.el8_4.x86_64 x86_64
`
* postgres_exporter version:

`psql (PostgreSQL) 9.6.22
`
* postgres_exporter flags:

```
    'DATA_SOURCE_NAME' => 'user=postgres host=/var/run/postgresql/ sslmode=disable',
```

* PostgresSQL version:

`bash-4.4$ /usr/pgsql-9.6/bin/postgres -V
postgres (PostgreSQL) 9.6.22
bash-4.4$
`
* Logs:
```
```

**Comment by david-peters-aitch2o** [comment]
for some reason the WAL had to be fixed and alertmanager started properly by removing the WAL files (runs out of memory quickly before WAL files are done) and now  works

**Comment by jurim76** [comment]
I didn't find this metric in postgres exporter code
