### ISSUE TITLE
On Doing service down or deleting postgres container, Metrics is set to 0 

### ISSUE THREAD

**Issue by oumkale** [prometheus-community/postgres_exporter#575]
## Proposal
**Use case. Why is this important?**
      Want to see with the master-slave HA cluster is doing read and write queries by taking down master  but once it goes down it losses metrics and gets a star from 0 values.
   Same for network loss to master, or deleting Postgres container.
  
 
![Screenshot from 2021-09-06 14-30-06](https://user-images.githubusercontent.com/34105373/132190942-03932ec9-d1a7-4f59-9890-ba5847ed2419.png)

It should add the old master values into new metrics one.
*“Nice to have” is not a good use case. :)*
Have been trying to make network loss against master statefulset, in results metrics should remain and it should retain. Currently, it is getting override.

**Comment by SuperQ** [comment]
This is against Prometheus best practices. The exporter exposes exactly what the service exposes, it does not interpret or modify data.
