### ISSUE TITLE
--log.format="logger:stdout?json=true" no longer valid?

### ISSUE THREAD

**Issue by dtseiler** [prometheus-community/postgres_exporter#585]
**What did you do?**

Upgraded postgres_exporter from 0.8.0 to 0.10.0

**What did you expect to see?**

Normal operation upon restart.

**What did you see instead? Under which circumstances?**

```
postgres_exporter: error: unrecognized log format "logger:stdout?json=true", try --help
```

**Environment**

* System information:

```
Linux 5.4.0-1055-azure x86_64
```

Ubuntu 18.04 LTS

* postgres_exporter version:

```
postgres_exporter, version 0.10.0 (branch: HEAD, revision: 57719ba53cac428769aaf3c4c0bb742df3cfca98)
  build user:       root@4dcb2c7f1315
  build date:       20210709-11:49:20
  go version:       go1.16.5
  platform:         linux/amd64
```

* postgres_exporter flags:

```
--log.format=logger:stdout?json=true
--log.level=info
--disable-default-metrics
--extend.query-path=/opt/foo/postgresql_exporter/conf.d/database-queries.yaml
--web.listen-address=:10000
```

* PostgresSQL version:

```
PostgreSQL 12.8 (Ubuntu 12.8-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
```

Changing `--log.format` to just say `--log.format="json"` lets postgres_exporter start up fine. Does that lose the stdout spec though? I didn't see anything in the release notes or changelog about this, which appears to be a breaking change as the new version fails to start with the existing `log.format` specification.

**Comment by sysadmind** [comment]
Yeah the logging library changed around 0.10.0, so the flags changed as well. I don't think the `stdout` part matters any longer as the logs are always output to stdout

**Comment by dtseiler** [comment]
That's good to know. Might I suggest putting a note about this somewhere since it is a breaking change when upgrading from an earlier version? Unless it is noted somewhere and I just missed it.
