### ISSUE TITLE
Adding new metrics via a environment variable

### ISSUE THREAD

**Issue by springfan** [prometheus-community/postgres_exporter#593]
## Proposal
**Use case. Why is this important?**

Passing over queries via queries.yaml results in the file being baked into the Docker image (at last in my kubernetes setup). In order to update the queries I must re-deploy my service. It would be useful to allow passing over the queries.yaml content via an environment variable to update existing deployments.

**Comment by SuperQ** [comment]
I'm planning to deprecate the queries.yaml. It's an anti-pattern for this exporter.

If you want a generic SQL exporter, try https://github.com/free/sql_exporter.
