### ISSUE TITLE
Binaries for v0.10.1 unavailable

### ISSUE THREAD

**Issue by joancafom** [prometheus-community/postgres_exporter#605]
**What did you do?**

Hi!

Recently, a new version of Postgres Exporter (v0.10.1) has been tagged and published [on the releases page](https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.10.1). Past version releases included both the source code and some compiled binaries, as well as a brief changelog. For instance, see [v0.10.0](https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.10.0).

This does not seem to be the case for v0.10.1. Will you be publishing the binaries for this version any time soon?

**What did you expect to see?**

The binaries for version `0.10.1` are available on the releases page.

**What did you see instead? Under which circumstances?**

No binaries, just the source code in `.zip` and `.tar.gz` format.

**Environment**

NA

**Comment by SuperQ** [comment]
Sorry, I forgot to mark the draft release as published. It's live now.
