### ISSUE TITLE
Error opening connection to database

### ISSUE THREAD

**Issue by rahmatov** [prometheus-community/postgres_exporter#606]
Hi. I am trying to get metrics of PG, but it fails. 
I have configured the .env file like that:

`DATA_SOURCE_NAME="postgresql://user@localhost:5432/?sslmode=disable"`

But I am getting this error:

`caller=log.go:168 level=error err="Error opening connection to database (postgresql://user:PASSWORD_REMOVED@localhost:5432/?sslmode=disable): pq: password authentication failed for user \"user\"`

**Comment by sysadmind** [comment]
This sounds like an authentication issue on the postgres side. Maybe password auth is disabled or the password is incorrect? 

Take a look at the help channels here for support questions: https://prometheus.io/community/
