### ISSUE TITLE
Implement default queries in the format of queries.yaml

### ISSUE THREAD

**Issue by pvid** [prometheus-community/postgres_exporter#622]
## Proposal

Unify the way user queries and built-in default queries are implemented in the form of a canonical `queries.yaml` files containing default metrics

**Use case. Why is this important?**

It would allow users to customize default queries by patching the official default `queries.yaml` file.

My use case is aggregation of per database metrics for a postgres cluster that contains a few thousand databases.

**Comment by sysadmind** [comment]
This project is currently moving the other direction. We are moving the useful parts of queries.yaml into the exporter itself. The queries file causes a lot of confusion for users and it is a pain to support. There are already exporters that handle custom queries (see https://github.com/free/sql_exporter).
