### ISSUE TITLE
update the mirror

### ISSUE THREAD

**Issue by freemankevin** [prometheus-community/postgres_exporter#628]
Is this project not maintained? The mirror version on the dockerhub warehouse is a bit lagging behind the latest development progress. Can you upload the latest versions of the docker mirror?
![image](https://user-images.githubusercontent.com/71524776/162385849-0b4df9da-b83c-41fe-818f-1a0cbddfb785.png)

**Comment by DasSkelett** [comment]
This project has been incorporated into the Prometheus-Community organization [more than a year ago](https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.9.0).

The new image locations are [quay.io/prometheuscommunity/postgres-exporter](https://quay.io/repository/prometheuscommunity/postgres-exporter?tab=tags&tag=latest) and [docker.io/prometheuscommunity/postgres-exporter](https://hub.docker.com/r/prometheuscommunity/postgres-exporter).
