### ISSUE TITLE
Scan error on column index 2, name \"checkpoint_write_time\": converting driver.Value type float64 (\"6.594096e+06\") to a int: invalid syntax

### ISSUE THREAD

**Issue by ekzyis** [prometheus-community/postgres_exporter#633]
**What did you do?**

```
$ git clone https://github.com/prometheus-community/postgres_exporter
$ cd postgres_exporter
$ make build
$ DATA_SOURCE_NAME="postgresql://postgres:password@localhost:5432/postgres?sslmode=disable" ./postgres_exporter
``` 

Different terminal:

```
$ curl localhost:9187/metrics
```

**What did you expect to see?**

No error in logs

**What did you see instead? Under which circumstances?**

Error in exporter:

```
ts=2022-04-17T19:30:00.357Z caller=collector.go:196 level=error msg="collector failed" name=bgwriter duration_seconds=0.002077823 err="sql: Scan error on column index 2, name \"checkpoint_write_time\": converting driver.Value type float64 (\"6.594096e+06\") to a int: invalid syntax"
```

**Environment**

* System information: Linux 5.10.109-1-MANJARO x86_64

* postgres_exporter version:

```
postgres_exporter, version 0.10.1 (branch: master, revision: 92bdb8755de886b2366de245e559538030ba3668)
  build user:       ekzyis@ekzyis-n131wu
  build date:       20220417-19:23:22
  go version:       go1.18
  platform:         linux/amd64
```

* postgres_exporter flags: no flags

* PostgreSQL version: 13.6 using this image: `timescale/timescaledb:2.6.1-pg13`

* Logs: no logs

**Comment by ekzyis** [comment]
What is interesting, on the same machine, using the docker command, it works 

```
docker run \
  --net=host \
  -e DATA_SOURCE_NAME="postgresql://postgres:password@localhost:5432/postgres?sslmode=disable" \
  quay.io/prometheuscommunity/postgres-exporter
```

On a different machine, both commands work.

The other machine output of `uname -srm`: Linux 5.10.96-1-MANJARO x86_64

**Comment by vishal-h** [comment]
```
--- a/collector/pg_stat_bgwriter.go
+++ b/collector/pg_stat_bgwriter.go
@@ -126,7 +126,7 @@ func (PGStatBGWriterCollector) Update(ctx context.Context, server *server, ch ch

        var cpt int
        var cpr int
-       var cpwt int
+       var cpwt float64
        var cpst int
        var bcp int
        var bc int
```

This fixes the issue.

**Comment by avdicl** [comment]
> ```
> --- a/collector/pg_stat_bgwriter.go
> +++ b/collector/pg_stat_bgwriter.go
> @@ -126,7 +126,7 @@ func (PGStatBGWriterCollector) Update(ctx context.Context, server *server, ch ch
> 
>         var cpt int
>         var cpr int
> -       var cpwt int
> +       var cpwt float64
>         var cpst int
>         var bcp int
>         var bc int
> ```
> 
> This fixes the issue.

Wondering if we can get this minor change merged in for the next release?

**Comment by n-rodriguez** [comment]
> Wondering if we can get this minor change merged in for the next release?

Please! Thank you!

**Comment by n-rodriguez** [comment]
Will also need this one : https://github.com/prometheus-community/postgres_exporter/pull/667

Thank you!

**Comment by weastur** [comment]
Hello!

When will the next release be? This error breaks the latest one.

**Comment by leahoswald** [comment]
Still no release despite the current one is broken :(

**Comment by copolycube** [comment]
Hello, I just tested the 0.11.1 (current latest) and this error is not present in the logs
