### ISSUE TITLE
Does it work with postgres 14?

### ISSUE THREAD

**Issue by PhilipMay** [prometheus-community/postgres_exporter#651]
The README.md sais:

> CI Tested PostgreSQL versions: 9.4, 9.5, 9.6, 10, 11, 12, 13

So what I as a user now thinks: "Does it work with version 14 of postgres?"

Can you maybe add something about this?

**Comment by PhilipMay** [comment]
Hi @sysadmind or @paulfantom - maybe one of you can help me here?

**Comment by TipTopBY** [comment]
I did not earn from the "box".
The error is the following:
An error has occurred while serving metrics:

11 error(s) occurred:
* collected metric pg_settings_check_function_bodies label:<name:"server" value:"dev-postgres.test:5432" > gauge:<value:1 >  has help "Check routine bodies during CREATE FUNCTION and CREATE PROCEDURE." but should have "Check function bodies during CREATE FUNCTION."
* collected metric pg_settings_data_directory_mode label:<name:"server" value:"dev-postgres.test:5432" > gauge:<value:700 >  has help "Shows the mode of the data directory." but should have "Mode of the data directory."
* collected metric pg_settings_enable_partition_pruning label:<name:"server" value:"dev-postgres.test:5432" > gauge:<value:1 >  has help "Enables plan-time and execution-time partition pruning." but should have "Enables plan-time and run-time partition pruning."
* collected metric pg_settings_idle_in_transaction_session_timeout_seconds label:<name:"server" value:"dev-postgres.test:5432" > gauge:<value:0 >  has help "Sets the maximum allowed idle time between queries, when in a transaction. [Units converted to seconds.]" but should have "Sets the maximum allowed duration of any idling transaction. [Units converted to seconds.]"
* collected metric pg_settings_integer_datetimes label:<name:"server" value:"dev-postgres.test:5432" > gauge:<value:1 >  has help "Shows whether datetimes are integer based." but should have "Datetimes are integer based."
* collected metric pg_settings_jit_debugging_support label:<name:"server" value:"dev-postgres.test:5432" > gauge:<value:0 >  has help "Register JIT-compiled functions with debugger." but should have "Register JIT compiled function with debugger."
* collected metric pg_settings_jit_optimize_above_cost label:<name:"server" value:"dev-postgres.test:5432" > gauge:<value:500000 >  has help "Optimize JIT-compiled functions if query is more expensive." but should have "Optimize JITed functions if query is more expensive."
* collected metric pg_settings_jit_profiling_support label:<name:"server" value:"dev-postgres.test:5432" > gauge:<value:0 >  has help "Register JIT-compiled functions with perf profiler." but should have "Register JIT compiled function with perf profiler."
* collected metric pg_settings_log_min_duration_statement_seconds label:<name:"server" value:"dev-postgres.test:5432" > gauge:<value:-1 >  has help "Sets the minimum execution time above which all statements will be logged. [Units converted to seconds.]" but should have "Sets the minimum execution time above which statements will be logged. [Units converted to seconds.]"
* collected metric pg_settings_log_transaction_sample_rate label:<name:"server" value:"dev-postgres.test:5432" > gauge:<value:0 >  has help "Sets the fraction of transactions from which to log all statements." but should have "Set the fraction of transactions to log for new transactions."
* collected metric pg_settings_parallel_tuple_cost label:<name:"server" value:"dev-postgres.test:5432" > gauge:<value:0.1 >  has help "Sets the planner's estimate of the cost of passing each tuple (row) from worker to leader backend." but should have "Sets the planner's estimate of the cost of passing each tuple (row) from worker to master backend."

**Comment by PhilipMay** [comment]
Thanks. :-)
