### ISSUE TITLE
Postgres Exporter not appearing in Prometheus Targets

### ISSUE THREAD

**Issue by arbianqx** [prometheus-community/postgres_exporter#656]
Hi guys,

I've been messing for a couple of days now with this issue and I can't seem to figure it out. Maybe a bug maybe something is off, I'm not sure.

**What did you do?**
I installed prometheus-operator via helm. Afterwards I installed postgres_exporter via helm with these values:
serviceMonitor:
  enabled: true
  namespace: monitoring-dev
  labels:
    release: prometheus
  telemetryPath: /metrics
  
config:
  datasource:
    # Specify one of both datasource or datasourceSecret
    host: 
    user: 
    # Only one of password, passwordSecret and pgpassfile can be specified
    password: 
    port: ""
    database: ''
    sslmode: disable
    extraParams: ''

service:
  type: ClusterIP
  port: 80
  targetPort: 9187
  name: http
  labels:
    release: prometheus
  annotations: {}

I also tried to check the labels and annotations from other servicemonitors to see if everything checks, but still this exporter isn't showing in my targets list?

Is this a bug or perhaps I'm doing something wrong.
Thanks in advance!

**Comment by sysadmind** [comment]
The helm chart is hosted in the repo https://github.com/prometheus-community/helm-charts. 
I'm not sure why you're having the issue, but there are a ton of variables. The best route for support is probably the mailing list here https://groups.google.com/forum/#!forum/prometheus-users
