### ISSUE TITLE
No result of postgresql_errors_total metrics for alert Postgresql high rate statement timeout

### ISSUE THREAD

**Issue by AakarshitAgarwal** [prometheus-community/postgres_exporter#662]
**What did you do?**

deploy postgres-exporter, and tried a lot of queries.

**What did you expect to see?**

I want to see metrics related to postgresql_errors_total so that I could fetch type of error from it like "statement_timeout" etc.,but I am not able to get any metrics related to it. Do postgres-exporter provide this metric?
I want to set the alert as [Postgresql high rate statement timeout](https://awesome-prometheus-alerts.grep.to/rules#postgresql:~:text=2.2.13.-,Postgresql%20high%20rate%20statement%20timeout,-Postgres%20transactions%20showing), can I do so in any other way?

**What did you see instead? Under which circumstances?**

Not able to grep any metric related to statement_timeout from exposed metrics

* System information:

Linux 3.10.0-1160.59.1.el7.x86_64 x86_64

* postgres_exporter version:

 postgres_exporter_v0.5.1

* postgres_exporter flags:

```
insert list of flags used here
```

* PostgreSQL version:

using the image of postgres:13.3-alpine

* Logs:
```
○ → curl http://localhost:9187/metrics | grep errors_total  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                 Dload  Upload   Total   Spent    Left  Speed
100  126k  100  126k    0     0  3663k      0 --:--:-- --:--:-- --:--:-- 3731k
```

**Comment by sysadmind** [comment]
I'm not sure where that metric would come from. This exporter exposes metrics with a `pg_` prefix, not `postgres_` so I'm not sure what exporter would provide that metric. If there is a field in a database that provides the data that you are looking for, that could be added.

**Comment by AakarshitAgarwal** [comment]
@sysadmind Yes metrics provided are with the prefix `pg_`, but if we can get any metrics exposed related to errors in Postgres, then we can easily differentiate its type.
And further, set the alert as [Postgresql high rate statement timeout](https://awesome-prometheus-alerts.grep.to/rules#postgresql:~:text=2.2.13.-,Postgresql%20high%20rate%20statement%20timeout,-Postgres%20transactions%20showing)
