### ISSUE TITLE
How to start postgres_exporter.exe???

### ISSUE THREAD

**Issue by liyouguang** [prometheus-community/postgres_exporter#693]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* postgres_exporter version:

	insert output of `postgres_exporter --version` here

* postgres_exporter flags:

```
insert list of flags used here
```

* PostgreSQL version:

	insert PostgreSQL version here

* Logs:
```
insert logs relevant to the issue here
```

**Comment by sysadmind** [comment]
It is unclear what you are asking because you did not fill out any of the information in the issue template.
