### ISSUE TITLE
Clarify documentation: provide info about default folder at which configration file is located by default

### ISSUE THREAD

**Issue by KES777** [prometheus-community/postgres_exporter#708]
**What did you do?**
Trying to find where configuration file is located

https://github.com/prometheus-community/postgres_exporter#configuration-file

**What did you expect to see?**
Documentation about default path

**What did you see instead?**
Nothing.

**Comment by sysadmind** [comment]
The `--config.file` option is the relative or absolute path to the config file. If the file path is relative, it's relative to the current context of the process. The README says that by default, this path is postgres_exporter.yml which is a relative path which means inside the current directory.
