### ISSUE TITLE
postgres_exporter left more and more conntions in database and not released or reuse them 

### ISSUE THREAD

**Issue by sheenzxx** [prometheus-community/postgres_exporter#727]
when use postgres_exporter to monitor pg database,

postgres_exporter left more and more connections in database and not released or reuse them

![1669889809(1)](https://user-images.githubusercontent.com/3350015/205027177-5bf8a7ac-278c-4b67-8498-f7c2cac78fe2.png)

then on other windows to request metrics

curl "http://localhost:9187/probe?auth_module=foo1&target=192.168.74.94:5433/pcauto"

query 
select datid,pid,usename,query_start from pg_stat_activity where usename='exporter_monitor' order by query_start

can see that when request 1 time .1 more connection add and not released or reuse
![1669889957(1)](https://user-images.githubusercontent.com/3350015/205027616-cce30d87-5833-496e-84ed-6f48929e7164.png)

**Comment by sheenzxx** [comment]
if there any Perfect solution？

**Comment by hajdukda** [comment]
ok this one is super important to fix.

**Comment by kjbass** [comment]
Yeah, another +1 for this being an important one to fix.  Running the exporter caused number of connections to go up endlessly.  @sheenzxx's solution seems like a valid one, but another option would be actually closing the connection after a probe finishes.

**Comment by kjbass** [comment]
> Yeah, another +1 for this being an important one to fix. Running the exporter caused number of connections to go up endlessly. @sheenzxx's solution seems like a valid one, but another option would be actually closing the connection after a probe finishes. Currently, cannot really use this in prod.

I might try my hand at fixing this one, think this shouldn't be too terrible to auto-close after probing.

**Comment by kjbass** [comment]
Tried my hand at writing a fix here: https://github.com/prometheus-community/postgres_exporter/pull/734

**Comment by kazauwa** [comment]
This bug can easily bring the production database down. This is what we saw yesterday after enabling `postgres_exporter`. We definitely need [https://github.com/prometheus-community/postgres_exporter/pull/734](734) merged.
<img width="783" alt="Screenshot 2023-02-01 at 12 22 38" src="https://user-images.githubusercontent.com/12330159/215946803-85cf7320-d640-4995-bcb9-29b8a09f4ddb.png">

**Comment by MichaelDBA** [comment]
Doesn't the error message indicate its a configuration problem?  --> error = empty dsn

So perhaps the connection is made nonetheless but unawares to the postgres_exporter so that's the reason its never closed.

**Comment by kjbass** [comment]
> Doesn't the error message indicate its a configuration problem? --> error = empty dsn
> 
> So perhaps the connection is made nonetheless but unawares to the postgres_exporter so that's the reason its never closed or assumed to be active in the first place.

I'm pretty sure that's a separate issue.  The `error = empty dsn` shows up regardless when you're using the multi-target exporter, but it's a bit of noise that does not affect things.  When using the multi target exporter you do not set a DSN, since you are targeting multiple instances with the probes.  

I think in general the multi target exporting could use some more love, but triaging the runaway connections is a good first step.
