### ISSUE TITLE
Add label per datasource

### ISSUE THREAD

**Issue by florianbeer** [prometheus-community/postgres_exporter#743]
We are scraping metrics for multiple instances for each postgres_exporter we have running. It would be nice to be able to add a label (for example an internal instance name) to each datasource connection string so we can better identify them in our queries and dashboards. At the moment we only have the `instance` label filled with hostname and port (e.g. localhost:50158) which is not very descriptive.

I'd like to add a label to my datasource connection string. For instance:
```
DATA_SOURCE_NAME='postgresql://postgres_exporter:xxxxx@localhost:50158/postgres?sslmode=disable&instance_name=website-production
```

**Comment by florianbeer** [comment]
> Maybe try the new [multi-target support](https://github.com/prometheus-community/postgres_exporter#multi-target-support-beta).

I've looked at it but I don't see how that would help me with getting a custom label for each instance.

**Comment by sysadmind** [comment]
Are you not able to add the label from the prometheus scrape configuration?

**Comment by florianbeer** [comment]
> Are you not able to add the label from the prometheus scrape configuration?

No, because I have one exporter per server and each server has a few dozens o f postgres instances.

**Comment by SuperQ** [comment]
Yes, this is up to your service discovery. Labeling of instances is a Prometheus config / discovery problem. This is out of scope for the postgres_exporter.
