### ISSUE TITLE
Disable collector bgwriter doesn't work

### ISSUE THREAD

**Issue by sinacek** [prometheus-community/postgres_exporter#749]
**What did you do?**
I would like to disable bgwriter collector by `--collector.bgwriter=false` when default value is `true`

**What did you expect to see?**

Disabled bgwriter collector. 

**What did you see instead? Under which circumstances?**
K8s report
```
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1

```

**Environment**

* System information:

quay.io/prometheuscommunity/postgres-exporter:v0.11.1
Linux 5.15.0-1029-azure x86_64

* postgres_exporter version:

postgres_exporter, version 0.11.1 (branch: HEAD, revision: b5fd2465646a09bb1c8dbd5c9c00b852da93927a)
  build user:       root@a2c981f603ff
  build date:       20220818-20:58:17
  go version:       go1.18.5
  platform:         linux/amd64

* postgres_exporter flags:

```
      --extend.query-path=/etc/config.yaml
      --web.listen-address=:9187
      --collector.bgwriter=false
      --disable-default-metrics
      --disable-settings-metrics
      --auto-discover-databases
      --exclude-databases
      postgres,template0,template1
      --include-databases
      stage
      --log.level=warn

```

* PostgreSQL version:

13.8

* Logs:
```
I didn't get any logs
```

**Comment by sysadmind** [comment]
To disable, the flag is actually `--no-collector.bgwriter`. This is due to the way the flag library works. 
https://github.com/alecthomas/kingpin/tree/v2.2.6#boolean-values

**Comment by sysadmind** [comment]
I wish this was in the help, but unfortunately the kingpin flag library does not support it.
