### ISSUE TITLE
Error opening config file postgres_exporter.yml in logs

### ISSUE THREAD

**Issue by maikelpoot** [prometheus-community/postgres_exporter#794]
**What did you do?**
Install/Upgrade to 0.12.0

Tried to add `--config.file=''` and `--config.file='false'` to disable the config file feature but it keeps trying to read the config file. 
Also a default of 'postgres_exporter.yml' doesn't really specify where this file should be located.

**What did you expect to see?**
No errors in the logs

**What did you see instead? Under which circumstances?**
Error in the logs
```
caller=main.go:86 level=error msg="Error loading config" err="Error opening config file \"postgres_exporter.yml\": open postgres_exporter.yml: no such file or directory"
```
**Environment**

* System information:

`Linux 3.10.0-1160.88.1.el7.x86_64 x86_64`

* postgres_exporter version:

```
# postgres_exporter --version
postgres_exporter, version 0.12.0 (branch: HEAD, revision: f9a1edbbc6d629663aa658378e1d989293e6e488)
  build user:       root@463311dfdfb6
  build date:       20230321-23:52:03
  go version:       go1.20.2
  platform:         linux/amd64
  tags:             netgo static_build
```
* postgres_exporter flags:

Contents of Defaults file:
```
### Managed by SaltStack
DATA_SOURCE_NAME=postgresql://postgres_exporter:********@127.0.0.1:5432/postgres?sslmode=disable
PG_EXPORTER_WEB_LISTEN_ADDRESS=:9187
PG_EXPORTER_DISABLE_DEFAULT_METRICS=false
PG_EXPORTER_DISABLE_SETTINGS_METRICS=false
PG_EXPORTER_EXTEND_QUERY_PATH=/usr/share/prometheus/queries.yaml
PG_EXPORTER_AUTO_DISOVER_DATABASES=true
PG_EXPORTER_EXCLUDE_DATABASES=template0,template1

POSTGRES_EXPORTER_OPTS="--extend.query-path=/usr/share/prometheus/queries.yaml --web.listen-address=:9187"
### EOF ###
```

* PostgreSQL version:

not relevant

* Logs:

**Comment by tuomotalvitie** [comment]
Personally, I was kind of hoping for `postgres_exporter.yml.example` file. I wonder if one can for example set dsn within.

> The PostgreSQL server's [data source name](http://en.wikipedia.org/wiki/Data_source_name) must be set via the DATA_SOURCE_NAME environment variable.

**Comment by hcastrofactored** [comment]
@maikelpoot did you figure it out? how should this file look like?

**Comment by sysadmind** [comment]
This log message has been changed to a warning. It is not actually an error. The next release will show this as a warning instead.

**Comment by mgalgs** [comment]
It still contains the word "error", which makes it seem like an error... If the config file isn't required I don't think there should be any message.

    time=2025-03-27T23:06:31.557Z level=WARN source=main.go:85 msg="Error loading config" err="Error opening config file \"postgres_exporter.yml\": open postgres_exporter.yml: no such file or directory"

Actually looks pretty scary and made me chase this down...
