### ISSUE TITLE
Server level metrics

### ISSUE THREAD

**Issue by rhegde2** [prometheus-community/postgres_exporter#798]
Hi Team, 

Is it possible to get the server level metrics(cpu, memory, disk, network) along with the postgres database metrics using this exporter?

Thanks,
Raghavendra

**Comment by SuperQ** [comment]
This is what the [node_exporter](https://github.com/prometheus/node_exporter) provides.

**Comment by mindw** [comment]
@SuperQ and for managed DBs like RDS Postgres? such metrics are only available via CloudWatch. 
Is there some way to extract them via a query assuming they are collected by Postgres in the first place?

**Comment by sysadmind** [comment]
I'm not sure that postgres exposes these stats via a table. The OS is much better at knowing these metrics. In case of RDS, there is a [cloudwatch exporter](https://github.com/prometheus/cloudwatch_exporter)
