### ISSUE TITLE
 to a float64: invalid syntax

### ISSUE THREAD

**Issue by Alexufo** [prometheus-community/postgres_exporter#850]
v0.13.1
pg: v15
ubuntu

In log:
pg_exporter       | ts=2023-06-28T21:12:09.788Z caller=collector.go:190 level=error msg="collector failed" name=replication duration_seconds=0.000349425 err="sql: Scan error on column index 0, name \"pg_postmaster_start_time\": converting driver.Value type time.Time (\"2023-06-27 21:20:59.88301 +0000 UTC\") to a float64: invalid syntax"
pg_exporter       | ts=2023-06-28T21:12:09.795Z caller=collector.go:190 level=error msg="collector failed" name=postmaster duration_seconds=0.007301787 err="sql: Scan error on column index 0, name \"pg_postmaster_start_time\": converting driver.Value type time.Time (\"2023-06-27 21:20:59.88301 +0000 UTC\") to a float64: invalid syntax"

**Comment by baerwang** [comment]
logger time output and error time inconsistency

<img width="2443" alt="image" src="https://github.com/prometheus-community/postgres_exporter/assets/52104949/9577c6fc-4143-41c4-9f94-25bcb78885e8">

**Comment by sysadmind** [comment]
This was fixed in #828 and will be part of the next release.
