### ISSUE TITLE
Offline build

### ISSUE THREAD

**Issue by musikid** [prometheus-community/postgres_exporter#851]
## Proposal

Similar to https://github.com/prometheus/node_exporter/issues/271, it isn't easily possible to build the exporter without internet access, due to the fact that promu is a phony target and the directory in which the initial path target "$PROMU" is set to FIRST_GOPATH. 
This makes it difficult to build the exporter in isolated environments.

## Solution

We could modify the Makefile.common like in https://github.com/prometheus/node_exporter/pull/272, but I'm wondering if it wouldn't be better to add it to the main prometheus project.

**Comment by SuperQ** [comment]
Makefile.common is synced from `prometheus/prometheus`. Those changes were made many years ago and were synced here a long time ago.
