### ISSUE TITLE
pg_database_size_bytes deprecated?

### ISSUE THREAD

**Issue by Dan-Sun** [prometheus-community/postgres_exporter#868]
**What did you do?**
Updated to latest version of postgres_exporter.

**What did you expect to see?**
`pg_database_size_bytes` availability.

**What did you see instead? Under which circumstances?**
Not available anymore? Deprecated?

**Environment**

* System information:

        Arch Linux

* postgres_exporter version:

        0.13.1

* postgres_exporter flags:

        no flags

* PostgreSQL version:

        15.3

**Comment by SuperQ** [comment]
That metric is provided by `--collector.database` and is enabled by default.

**Comment by Dan-Sun** [comment]
Thank you for the info.
It must have been a hiccup after updating the exporter or the server. It works again now.
