### ISSUE TITLE
Error on converting start_time, invalid syntax

### ISSUE THREAD

**Issue by crankedguy** [prometheus-community/postgres_exporter#884]
Hello, 

I am getting the following error running the exporter.
Is this something known about?

PostgreSQL 15.3.1 on Alma 9.2

` postgres_exporter[940973]: ts=2023-08-09T05:18:04.829Z caller=collector.go:190 level=error msg="collector failed" name=postmaster duration_seconds=0.000335961 err="sql: Scan error on column index 0, name \"pg_postmaster_start_time\": converting driver.Value type time.Time (\"2023-08-08 07:23:55.278047 +0200 CEST\") to a float64: invalid syntax"`

**Comment by sysadmind** [comment]
Use [v0.13.2](https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.13.2)
