### ISSUE TITLE
One question: why some parameters related automatically discover databases and a config file will be DEPRECATED.

### ISSUE THREAD

**Issue by Telzeng** [prometheus-community/postgres_exporter#886]
**What did you do?**
Just check the Readme documents.  One question: 
why will some parameters related "automatically discover databases" and "a config file be DEPRECATED"?
##
auto-discover-databases (DEPRECATED) Whether to discover the databases on a server dynamically. Default is false.

extend.query-path (DEPRECATED) Path to a YAML file containing custom queries to run. Check out [queries.yaml](https://github.com/prometheus-community/postgres_exporter/blob/master/queries.yaml) for examples of the format.

dumpmaps Do not run - print the internal representation of the metric maps. Useful when debugging a custom queries file.

constantLabels (DEPRECATED) Labels to set in all metrics. A list of label=value pairs, separated by commas.

version Show application version.

exclude-databases (DEPRECATED) A list of databases to remove when autoDiscoverDatabases is enabled.

include-databases (DEPRECATED) A list of databases to only include when autoDiscoverDatabases is enabled.

##

**What did you expect to see?**

Hello Experts,

we are using the metrics. but I noticed that the latest version talked that some parameters related "automatically discover databases" and "a config file" will be DEPRECATED.  Could you explain why? 
I guess that the new feature "Multi-Target Support" will have the same function as these parameters or not need them?

Thanks very much.
Telzeng

**Comment by Telzeng** [comment]
Hello Experts,

Do you have some updates on it? Thanks in advance.

Thanks very much.
Telzeng

**Comment by Telzeng** [comment]
Hi @richardnpaul,

Thanks for your reply.
Another parameter related "auto-discover-databases"  will be DEPRECATED. Could you explain why remove it? 

Thanks
Telzeng

**Comment by Efiartes** [comment]
I need to monitor some query results not exposed as metric by the exporter, is there another way to do custom query and export the results?

**Comment by SuperQ** [comment]
The auto-discover-databases is deprecated as part of the queries.yaml removal. For collectors that pertain to internal PostgreSQL table metrics, we're going to have a new include/exclude filter flags to handle that on a per-collector basis. The original exporter design was a bit of a mess in this regard and we have been doing refactoring to get us in a better place to support this.

* Queries that pertain to PostgreSQL server metrics should be added as new collectors in the collectors package. Feel free to file new issues detailing the specific metrics and queries that you would like to monitor.
* Queries that are business domain, things that pertain to the contents of tables, should use a more appropriate exporter like the [sql_exporter](https://github.com/justwatchcom/sql_exporter) or [query-exporter](https://github.com/albertodonato/query-exporter).

**Comment by SuperQ** [comment]
I've filed https://github.com/prometheus-community/postgres_exporter/issues/964 to track the flag cleanup.
