### ISSUE TITLE
ERROR:  column pg_stat_statements.total_time does not exist at character 141

### ISSUE THREAD

**Issue by strafer** [prometheus-community/postgres_exporter#889]
**What did you do?**

  I'm deploying an exporter for a DBMS with the `pg_stat_statements` extension enabled.

**What did you expect to see?**

  Error-free proceeding, availability of required metrics.

**What did you see instead? Under which circumstances?**

  Error in the DBMS log every time metrics are collected.

I assume this is related to [this](https://github.com/prometheus-community/postgres_exporter/blob/master/collector/pg_stat_statements.go#L79) query in the `pg_stat_statements` collector.
I don't really see the `total_time` column in the `pg_stat_statements` view, although I can see all the other columns from this query.

**Environment**

* System information:

  `Linux 5.10.0-23-amd64 x86_64`

* postgres_exporter version:

  ```
  postgres_exporter, version 0.13.2 (branch: HEAD, revision: 8c3604b85e38ae7141e84ecdc318b6015a196c97)
    build user:       root@2ea2be721819
    build date:       20230724-00:08:19
    go version:       go1.20.6
    platform:         linux/amd64
    tags:             netgo static_build
  ```

* postgres_exporter flags:

  ```
  --log.level=info
  --log.format=json
  --web.config.file=/etc/postgres-exporter/web_config.yaml
  --web.listen-address=:9188
  --collector.stat_statements
  --disable-settings-metrics
  --no-collector.replication
  --no-collector.replication_slot
  ```

* PostgreSQL version:
  `15.3`
	
* Logs:
  ```
  ERROR:  column pg_stat_statements.total_time does not exist at character 141
  ```

**Comment by jiangjian0920** [comment]
#875

**Comment by strafer** [comment]
I apologize, I was looking only among the open issues and therefore did not find this. Thank you.
