### ISSUE TITLE
Not possible to use the PGStatDatabaseCollector with NewPostgresCollector

### ISSUE THREAD

**Issue by Jrmy2402** [prometheus-community/postgres_exporter#935]
Hi,
**What did you do?**
I try to use the collector as a lib inside a golang application like this: 

```
         connStr := "postgresql://user:password@localhost:5432/test"
	pgCollector, err := collector.NewPostgresCollector(logger.New(""), []string{}, connStr, []string{})
	if err != nil {
		panic(err) // handle error
	}
	
	pgCollector.Collectors = map[string]collector.Collector{
		"database":                 collector.PGDatabaseCollector{},
		"stat_bgwriter":            collector.PGStatBGWriterCollector{},
		//"stat_database":            collector.PGStatDatabaseCollector{},
		"locks":                    collector.PGLocksCollector{},
		"stat_activity_autovacuum": collector.PGStatActivityAutovacuumCollector{},
	}

	prometheus.MustRegister(pgCollector)
	http.Handle("/metrics", promhttp.Handler())
```

**What did you expect to see?**
But I cannot use the stat_database because of this:

> Cannot use 'collector.PGStatDatabaseCollector{}' (type collector.PGStatDatabaseCollector) as the type collector.Collector Type does not implement 'collector.Collector' as the 'Update' method has a pointer receiver

I don't know If I used the NewPostgresCollector correctly or not, I tried without defining the pgCollector.Collectors but all metrics are disabled.

**Postgres_exporter version:**
	**v0.14.0**

Thanks

**Comment by sysadmind** [comment]
I don't believe that we make any promises about using the exporter as a library. The error you have is because the `Update` method of `PGStatDatabaseCollector` takes a pointer receiver. You have to use a pointer to it. I suspect there are other pieces you're missing here as well.
