### ISSUE TITLE
postgres_exporter-0.14.0.windows运行提示无yml文件

### ISSUE THREAD

**Issue by WindOfFree** [prometheus-community/postgres_exporter#947]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* postgres_exporter version:

	insert output of `postgres_exporter --version` here

* postgres_exporter flags:

```
insert list of flags used here
```

* PostgreSQL version:

	insert PostgreSQL version here

* Logs:
```
insert logs relevant to the issue here
```

**Comment by WindOfFree** [comment]
![image](https://github.com/prometheus-community/postgres_exporter/assets/36319009/c3174cd4-5351-4a08-b9b7-7ef5cbbb7878)

**Comment by sysadmind** [comment]
This log message is a warning. It does not prevent the exporter from being used. It is unclear what you are asking about. If there is something else that is unclear, please reopen and add those questions.
