### ISSUE TITLE
queries.yaml is empty

### ISSUE THREAD

**Issue by marekaf** [prometheus-community/postgres_exporter#955]
README states:

```
The -extend.query-path command-line argument specifies a YAML file containing additional queries to run. 
Some examples are provided in [queries.yaml](https://github.com/prometheus-community/postgres_exporter/blob/master/queries.yaml).
```

but queries.yaml is empty.

**Comment by SuperQ** [comment]
The extended query configuration is optional, as well as deprecated. There is no need for it.

**Comment by Efiartes** [comment]
The new/non-deprecated way is poorly documented, rendering doc useless:
https://github.com/prometheus-community/postgres_exporter#adding-new-metrics

There's a Python snippet that is supposed to be used for copying table descriptions from PostgreSQL documentation, supposing that I can get that output, wheres is supposed to be copied? The main configuration file only supports auth_modules related configuration.

One basic and complete example would be great.

**Comment by sebastiansterk** [comment]
@SuperQ Some more detailed documentation about this would be really helpful.

**Comment by jesayafn** [comment]
> The new/non-deprecated way is poorly documented, rendering doc useless: https://github.com/prometheus-community/postgres_exporter#adding-new-metrics
> 
> There's a Python snippet that is supposed to be used for copying table descriptions from PostgreSQL documentation, supposing that I can get that output, wheres is supposed to be copied? The main configuration file only supports auth_modules related configuration.
> 
> One basic and complete example would be great.

I confused with documentation for configure the python snippet will be use for exporter. Can someone give me a example tutorial for this? I need to add metric.
