### ISSUE TITLE
Adding connection limit stats for database and roles

### ISSUE THREAD

**Issue by jocelynthode** [prometheus-community/postgres_exporter#996]
## Proposal
Hey, at my company we're relying heavily on the postgres_exporter to monitor our PostgreSQL instances and we recently faced the issues where a project used all their alloted connections defined by a connection limit on the database and we had no way of seeing it in our Prometheus/Alertmanager setup.

I would like to contribute a collector to retrieve both the `pg_database_connection_limits` and `pg_roles_connection_limits`. Is this a feature the project would be interested? If yes I'll happily open a PR with these changes. (I already have an initial working code with no tests)

**Comment by SuperQ** [comment]
Yes, that sounds like perfectly reasonable collectors. Can you document what queries are required for this info?

One thing I'm working towards is consolidating similar collectors.

**Comment by jocelynthode** [comment]
Here are the required queries:
- As we filter database I have to do it one by one as we do for the database size `select pg_database.datconnlimit FROM pg_database WHERE pg_database.datname = $1`
- `select pg_roles.rolname,pg_roles.rolconnlimit FROM pg_roles`

I should have a PR ready either today or by the end of the week. It might be a WIP as I'm not familiar with the code base :)
